In [1]:
import numpy as np
import pandas as pd

#Read Data
from google.colab import files
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
# Question 1 --> Loading the dataset
bac = pd.read_csv('/content/drive/My Drive/Colab Notebooks/blogtext.csv')

In [97]:
bac_df=bac[:4000]
bac_df.head(8)

id  ...                                               text
0  2059027  ...             Info has been found (+/- 100 pages,...
1  2059027  ...             These are the team members:   Drewe...
2  2059027  ...             In het kader van kernfusie op aarde...
3  2059027  ...                   testing!!!  testing!!!          
4  3581210  ...               Thanks to Yahoo!'s Toolbar I can ...
5  3581210  ...               I had an interesting conversation...
6  3581210  ...               Somehow Coca-Cola has a way of su...
7  3581210  ...               If anything, Korea is a country o...

[8 rows x 7 columns]

In [98]:
bac_df.shape

(4000, 7)

In [0]:
#Question 2
# import and instantiate CountVectorizer (with the default parameters)
from sklearn.feature_extraction.text import CountVectorizer
cvect = CountVectorizer(stop_words='english',lowercase=True)
# Lowercase, stopwords have been forced. Unwanted spaces and characters are automatically removed unless included using token_pattern)

In [100]:
#Questions 3 
bac_df.dtypes

id         int64
gender    object
age        int64
topic     object
sign      object
date      object
text      object
dtype: object

In [101]:
bac_df['labels']=bac_df['gender']+bac_df['age'].astype(str)+bac_df['topic']+bac_df['sign']
bac_df.head(2)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


id  ...            labels
0  2059027  ...  male15StudentLeo
1  2059027  ...  male15StudentLeo

[2 rows x 8 columns]

In [102]:
bac_df1=bac_df.drop(['id','gender','age','topic','sign','date'],axis=1)
bac_df1.head(2)

text            labels
0             Info has been found (+/- 100 pages,...  male15StudentLeo
1             These are the team members:   Drewe...  male15StudentLeo

In [103]:
#Question 4: Separating Features and Labels, train/test split 
x=bac_df1['text']
y=bac_df1['labels']
print(x.head(2))
print(y.head(2))

0               Info has been found (+/- 100 pages,...
1               These are the team members:   Drewe...
Name: text, dtype: object
0    male15StudentLeo
1    male15StudentLeo
Name: labels, dtype: object


In [0]:
from sklearn.model_selection import train_test_split

In [0]:
# split X and y into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y,random_state=101)

In [106]:
##Training data
print(x_train.shape)
print(y_train.shape)

(3000,)
(3000,)


In [107]:
#Test data
print(x_test.shape)
print(y_test.shape)

(1000,)
(1000,)


In [108]:
#Questions 5 --> Vectorize the features
#Feed input data to CountVectorizer after including ngram
cvect = CountVectorizer(stop_words='english',lowercase=True,ngram_range=(1,2))
cvect.fit(x_train)

#Check the vocablury size
len(cvect.vocabulary_)


195848

In [0]:
#Convert Training/Test data Count Vectors
x_train_ct=cvect.transform(x_train)
x_test_ct=cvect.transform(x_test)

In [110]:
#Size of Document Term Matrix
print(x_train_ct.shape)
print(x_test_ct.shape)

(3000, 195848)
(1000, 195848)


In [111]:
#sparse matrix
print(x_train_ct[0])

  (0, 2011)	1
  (0, 2016)	1
  (0, 3324)	1
  (0, 3331)	1
  (0, 4337)	1
  (0, 4338)	1
  (0, 6025)	1
  (0, 6026)	1
  (0, 13920)	1
  (0, 13925)	1
  (0, 25145)	1
  (0, 25146)	1
  (0, 25399)	1
  (0, 25400)	1
  (0, 37440)	1
  (0, 37489)	1
  (0, 51112)	1
  (0, 51159)	1
  (0, 54031)	1
  (0, 54032)	1
  (0, 54580)	1
  (0, 54581)	1
  (0, 59127)	1
  (0, 59128)	1
  (0, 61228)	2
  :	:
  (0, 161200)	1
  (0, 164101)	1
  (0, 164134)	1
  (0, 166087)	1
  (0, 166118)	1
  (0, 166604)	1
  (0, 166610)	1
  (0, 166618)	1
  (0, 166619)	1
  (0, 169016)	1
  (0, 169017)	1
  (0, 172753)	1
  (0, 173106)	1
  (0, 175464)	1
  (0, 175506)	1
  (0, 176016)	1
  (0, 176021)	1
  (0, 176843)	1
  (0, 176884)	1
  (0, 179186)	1
  (0, 179187)	1
  (0, 185456)	1
  (0, 185593)	1
  (0, 191306)	1
  (0, 191330)	1


In [112]:
#Questions 6: Printing the dictionary
y_train.value_counts()

male35TechnologyAries        1728
female24indUnkScorpio         146
female15StudentLibra          101
male24EngineeringLibra         90
female27EducationAquarius      62
                             ... 
female36StudentGemini           1
female33indUnkSagittarius       1
female23indUnkAquarius          1
female27EducationGemini         1
female16indUnkSagittarius       1
Name: labels, Length: 69, dtype: int64

In [113]:
d=y_train.value_counts().to_dict()
d

{'female14indUnkAquarius': 4,
 'female14indUnkAries': 14,
 'female14indUnkCancer': 2,
 'female14indUnkLeo': 3,
 'female15ArtsPisces': 2,
 'female15StudentAquarius': 45,
 'female15StudentCancer': 7,
 'female15StudentGemini': 4,
 'female15StudentLeo': 11,
 'female15StudentLibra': 101,
 'female15indUnkAries': 16,
 'female16indUnkSagittarius': 1,
 'female16indUnkTaurus': 16,
 'female17StudentAries': 19,
 'female17StudentGemini': 8,
 'female17StudentLeo': 23,
 'female17StudentScorpio': 6,
 'female23indUnkAquarius': 1,
 'female23indUnkAries': 8,
 'female23indUnkLibra': 14,
 'female23indUnkSagittarius': 3,
 'female24BankingLibra': 2,
 'female24indUnkAries': 9,
 'female24indUnkScorpio': 146,
 'female25BusinessServicesAries': 18,
 'female25StudentTaurus': 26,
 'female25indUnkCapricorn': 2,
 'female25indUnkSagittarius': 2,
 'female25indUnkTaurus': 5,
 'female26AccountingAquarius': 2,
 'female26ScienceSagittarius': 2,
 'female27EducationAquarius': 62,
 'female27EducationGemini': 1,
 'female33Bank

In [114]:
d['male35TechnologyAries']

1728

In [0]:
#Questions 7 --> Transform the labels
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()



In [116]:
y_train1=mlb.fit_transform(y_train)
y_train1

array([[0, 1, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 1, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [1, 1, 0, ..., 0, 0, 0]])

In [117]:
mlb.classes_

array(['-', '1', '2', '3', '4', '5', '6', '7', '9', 'A', 'B', 'C', 'E',
       'G', 'I', 'L', 'M', 'N', 'P', 'R', 'S', 'T', 'U', 'V', 'a', 'b',
       'c', 'd', 'e', 'f', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 'o', 'p',
       'q', 'r', 's', 't', 'u', 'v', 'y'], dtype=object)

In [118]:
y_test1=mlb.fit_transform(y_test)
y_test1

array([[0, 1, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 0, 0, 0]])

In [0]:
#Question 8 - choosing a classifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression


In [0]:
clf=LogisticRegression(solver='lbfgs')
clf=OneVsRestClassifier (clf)


In [121]:
clf.fit(x_train_ct, y_train1)

/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label 24 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label 28 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label 34 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label 35 is present in all training examples.
  str(classes[c]))


OneVsRestClassifier(estimator=LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='auto',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='lbfgs', tol=0.0001,
                                                 verbose=0, warm_start=False),
                    n_jobs=None)

In [0]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing
from sklearn.metrics import f1_score,classification_report, confusion_matrix,accuracy_score

In [0]:
#Question 9 - Fitting the Classifier
y_predict = clf.predict(x_test_ct)



In [124]:
y_predict

array([[0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 1, 0, 0]])

In [0]:
y_predict1=mlb.inverse_transform(y_predict)

In [126]:
print(metrics.accuracy_score(y_test1, y_predict))

0.571


In [127]:
print(metrics.classification_report(y_test1, y_predict))

              precision    recall  f1-score   support

           0       0.87      0.26      0.40        50
           1       0.86      0.55      0.67       170
           2       0.63      0.39      0.48       181
           3       0.85      0.94      0.89       674
           4       0.60      0.27      0.37       125
           5       0.83      0.93      0.88       687
           6       0.57      0.12      0.21        32
           7       0.72      0.38      0.50        81
           8       0.00      0.00      0.00        22
           9       0.85      0.92      0.89       688
          10       1.00      0.45      0.62        33
          11       0.89      0.31      0.46        55
          12       0.68      0.25      0.36        61
          13       0.00      0.00      0.00         8
          14       1.00      0.55      0.71        22
          15       0.71      0.41      0.52       114
          16       0.00      0.00      0.00        18
          17       0.33    

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [128]:
#Question 10
print(y_test1,y_predict)

[[0 1 0 ... 1 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 1 0 ... 0 0 0]] [[0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 1 0 ... 1 0 0]]
